### ISSUE TITLE
Request / response option

### ISSUE THREAD

**Issue by percramer** [flq/MemBus#15]
Hi,

I have been looking at membus and it seems like it could really help me for Some software project. But i was wondering if there also is some sort of request / response message possible? So where i van publish a message and certain subscribers might answer it.

most of my programs are modular, meaning that certain modules are plain dll's which are loaded dynamically. These contain user controls etc. We now have an event system where a module can request settings and modules that are subscribed to this event will determine if the requested settings is from them and answer by giving the wanted information. So a module / plugin might need the connection string to the sql server. It will then make a request for the connection string and the main module will see this and respond with the correct answer. The current request contains a list of wanted settings, so each module that gets the event will go through the list and fill in his appropriate items.

I have been looking at RabbitMQ (which is totally different from yours of course) and they also have such a system. But i only need it in the application, so RabbitMQ give me a lot of overhead i don't want.

**Comment by flq** [comment]
Hi there,
for the task at hand I wouldn't necessarily use MemBus but rather some kind of IoC Container that could inject you with the dependency via an interface that all plugins can see.

As to the Request / Response paradigm, there is nothing built in per see, as the nature of this library is really asynchronous messaging.

The times where I would have liked a response, I used the concept of a correlation Id..

```csharp
    FooRequest {
      Guid CorrelationId;
      object Payload;
    }

    FooResponse {
      Guid CorrelationId;
      object Payload;
    }
    

    var correlationId = Guid.NewGuid();
    var dispose = bus.Observe<FooResponse>()
      .Where(fr => fr.CorrelationId == correlationId)
      .Subscribe(fr => {
        dispose.Dispose();
        // Handle response
      });

    bus.Publish(new FooRequest { CorrelationId = correlationId });
```

I hope this helps.

**Comment by percramer** [comment]
ok that might also work! But with an request / response system the code will wait until it has received answers from it's subscribers. In your sample, how will the code now if all subscribers have seen the request (and answered it).

**Comment by flq** [comment]
Maybe this kind of style does not fit your requirements. In a publish/subscribe system the publisher does not know how many recipients there are, or if there are any. My example shows a pattern where you expect a single response, but it already falls apart when you have multiple recipients.

If you really want request/response semantics membus may not be your best option.
