### ISSUE TITLE
When does it really make sense to use a project like MemBus vs Hangfire?

### ISSUE THREAD

**Issue by markalanevans** [flq/MemBus#18]
Our immediate need is background processing.
Both provide this, however management is full featured(built in UI) and deployment is simpler with Hangfire, but a service bus does seem like it could be more robust.

Aside from sending emails and post processing data. What are some pretty common examples that make using a Service Bus the right choice over http://hangfire.io/ when dealing with large web application?

**Comment by flq** [comment]
I haven't used hangfire yet, but from some preliminary investigations I'd rather use it for batching, fire & forget style scenarios where I want to pull off some long running task away from web requests. In that respect hangfire seems to provide plenty to ensure that tasks can be run even though IIS imposes some hard requirements on whether you are allowed to run your task until the end of the Application Pool.

A bus is generally more about how different concerns can interact with each other without muddling concerns like synchronicity and hard-linking into the equation. MemBus e.g. provides nothing with regard to making sure that some task will be allowed to complete in the ocntext of an IIS App-Pool. MemBus is just about communicating between disparate parts of your application, without even providing persistence.
